options:
  formatter: stylish
rules:
  pseudo-element: 0
  property-sort-order: 0
  no-css-comments: 0
  force-pseudo-nesting: 0
  force-attribute-nesting: 0
  no-qualifying-elements: 0
  clean-import-paths:
    - 1
    -
      filename-extension: 0
  no-color-literals:
    - 1
    -
      allow-rgba: 1
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
